### ISSUE TITLE
Security Incident

### ISSUE THREAD

**Issue by MartinBoernert** [rh4001/ChurchTools-Automations#1]
@rh4001 your credentials are exposed!

please change and clean your code ;-)

**Comment by MartinBoernert** [comment]
https://github.com/rh4001/ChurchTools-Automations/blob/81e00b3ffe0316d028551f4dabb946b5cbb9bd2b/secure/config.py

**Comment by rh4001** [comment]
@MartinBoernert Thank you for the warning. Have adjusted it and made the token unusable
